# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chealth.proto\x12\rserver_health\"C\n\x0cServerHealth\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08sessions\x18\x02 \x01(\r\x12\x14\n\x0cmax_sessions\x18\x03 \x01(\r\"c\n\x17GetServerHealthResponse\x12\x32\n\rserver_health\x18\x01 \x01(\x0b\x32\x1b.server_health.ServerHealth\x12\x14\n\x0clast_updated\x18\x02 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVERHEALTH._serialized_start=31
  _SERVERHEALTH._serialized_end=98
  _GETSERVERHEALTHRESPONSE._serialized_start=100
  _GETSERVERHEALTHRESPONSE._serialized_end=199
# @@protoc_insertion_point(module_scope)
