# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: health.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chealth.proto\x12\x06health\"C\n\x0cServerHealth\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08sessions\x18\x02 \x01(\r\x12\x14\n\x0cmax_sessions\x18\x03 \x01(\r\"\\\n\x17GetServerHealthResponse\x12+\n\rserver_health\x18\x01 \x01(\x0b\x32\x14.health.ServerHealth\x12\x14\n\x0clast_updated\x18\x02 \x01(\x01\x42\x08Z\x06healthb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006health'
  _globals['_SERVERHEALTH']._serialized_start=24
  _globals['_SERVERHEALTH']._serialized_end=91
  _globals['_GETSERVERHEALTHRESPONSE']._serialized_start=93
  _globals['_GETSERVERHEALTHRESPONSE']._serialized_end=185
# @@protoc_insertion_point(module_scope)
